### ISSUE TITLE
[FEAT] Move back to pinned version of alpine

### ISSUE THREAD

**Issue by mikecousins** [linuxserver/docker-transmission#286]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I think we should move back to a pinned version of alpine linux to avoid issues like upstream curl breakages.

### Reason for change

https://wiki.alpinelinux.org/wiki/Repositories#Edge

Edge should not be used except for testing. I don't see a good reason to be running this bleeding edge.

**Comment by Roxedus** [comment]
This change would mean there won't be transmission updates for 6 months at a time, which was the reason it was moved to edge in the first place.

**Comment by dubwoc** [comment]
Less updates for a venerable piece of software like Transmission seems like the steady state that is most desirable. 

Looking at 2023 4.0 was introduced, one of the largest changes in 3+ years and there were a total of 7 updates. Most of these updates were fixing bugs.  Which is probably a time to slow updates and wait for that dust to settle rather than chase them. 

In 2022 they had one release, in 2021 there were zero releases and in 2020 there was one release. 

A more stable version of alpine seems not only prudent but likely to have little effect on the users of this distribution of transmission. Given previous release history.

**Comment by ivanjx** [comment]
i am also for this. the transmission devs tested the stable releases against the libraries that are available at the time of release. we cant expect them to always anticipate for breaking changes of the underlying libraries being used.

also labeling the last libcurl bug as "upstream" issue is a bit misleading since it is clearly this project's issue that is always using bleeding edge version of the libraries.

**Comment by vincejv** [comment]
> labeling the last libcurl bug as "upstream" issue is a bit misleading since it is clearly this project's issue

other lsrio projects builds against alpine edge like the qbittorrent container, sure there are few issues from time to time, but not as severe as banning the use of a software

An exemption only accommodated and extended **solely** for transmission is questionable to me when the rest of the project *arrs, qbit, jellyfin, znc etc. have no severe issues, raises the question of why only transmission? Alpine edge doesn't mean a "snapshot" or "development" build of a dependency, for example, the buggy libcurl dependency was released in the **stable** version tree.

**Comment by drizuid** [comment]
we moved transmission to edge because everyone complained about delays in transmission updates; now everyone complains about the updates. we can't win :p 

for now, if you want an older version, pin the tag. We can internally discuss whether we want to maintain another tag to appease the minority wishing for the older alpine version based transmission

**Comment by vincejv** [comment]
or they can just not update transmission every time there's a new update with this docker container if they want to have an almost bug free experience.

**Comment by ivanjx** [comment]
i just realized that this project does not compile transmission and just pulling whatever alpine has. if so then edge version is required to get minor updates for transmission itself.

moving back to pinned version to alpine will require this project to recompile transmission from source first.
