### ISSUE TITLE
Configuration file not save

### ISSUE THREAD

**Issue by JrCs** [linuxserver/docker-transmission#39]
When the container is stop/kill, the configuration file is not save and we loose all the modifications done with the GUI.

**Comment by mist0706** [comment]
Also it seems that when an external settings.json file is supplied through the mapped /config directory the this is overwritten. Docker does not respect existing files when running a docker restart.

`root@deploy-test:/opt/transmission# md5sum settings.json
94c1c3c66f66b5a50fb87ac8aa8eeaf9  settings.json
root@deploy-test:/opt/transmission# docker restart transmission
transmission
root@deploy-test:/opt/transmission# md5sum settings.json
f503c71ac81c96936787b70af30d7ff4  settings.json
root@deploy-test:/opt/transmission# # putting back my own file
root@deploy-test:/opt/transmission# md5sum settings.json
94c1c3c66f66b5a50fb87ac8aa8eeaf9  settings.json
`
The docker config directory becomes completely useless due to this simple fact unless you either want to run with standard values or want to configure everything manually every time (since we cannot do graceful shutdowns)

**Comment by mist0706** [comment]
This is the salt state used for creating the files, user, docker and so on: https://thepasteb.in/p/nZhlNP5rQWJFY It should be easy to extrapolate what the docker create command would look like.

**Comment by aptalca** [comment]
I just tested this and I don't see any issues.

Transmission service is telling it to use /config folder as the settings folder, so the `settings.json` file in there is the one that is used by transmission. When settings are changed via gui, transmission does not write the new settings to that file right away. It only does so when transmission is shutting down. So if the container is killed (stopped unclean) the settings will not be written.

But a proper stop to the container allows transmission to write the settings to `/config/settings.json` before stopping cleanly.

@mist0706 with regards to supplying your own settings file, I'm assuming you are doing that while the container is running. What you're witnessing is that when the container is stopping cleanly, transmission overwrites the settings file with its cached settings (your custom file was never read by transmission), thereby overwriting your custom settings file. Either change the settings through the gui, or, copy your own settings file while the container is down, so transmission starts with your custom settings and they are cached.

**Comment by JrCs** [comment]
You need my PR #40 to close nicely transmission.

**Comment by aptalca** [comment]
Based on my tests with the latest image, it already closes nicely and saves its settings.

**Comment by lordjancso** [comment]
@aptalca Unfortunately that is not true.
I'm using the lastest version and it doesnt saves its settings.
Further more it restarts every downloaded torrent on startup.

**Comment by ThomasDK81** [comment]
@lordjancso: Sound like you have a problem with your volumes.

**Comment by lordjancso** [comment]
@ThomasDK81 here is my config. I dont have any idea what would be a problem here:

```
  transmission:
    image: linuxserver/transmission
    ports:
      - 9091:9091
    environment:
      PGID: 1000
      PUID: 1000
    volumes:
      - ./transmission/config:/config
```

**Comment by aptalca** [comment]
@lordjancso  `./transmission/config` is not an absolute path. What does it point to? Can you navigate to it on your host?

Regarding the settings, are you manually editing the settings file? If so, see my comment above.

I tested this by creating a fresh container, opening the gui, changing the speed limits and restarting the container. My changes were intact. Then I changed them again and restarted the container, again, changes are there. You need to be more specific about your use case scenario.

There is a separate issue about torrents not resuming, which is currently open because we didn't get a chance to look into it yet. This issue is just about the settings not being saved and I can't reproduce the issue mentioned.

**Comment by aptalca** [comment]
I figured out the issue. Transmission-daemon fails to stop with SIGTERM if there are active torrents. If no active torrents, TERM stops it.

See here for more info: https://github.com/linuxserver/docker-transmission/issues/24#issuecomment-346757483

**Comment by Fribb** [comment]
I have this issue but I don't have active torrents, all my torrents are finished but whenever the container is restarted or stopped and started the configuration file is overwritten.

I did it like you tested it @aptalca started the container, opened the gui and just changed the port. I then stopped the container, started it again and the config port was the default one.

I noticed that the config file has the file permission of 600 which I changed to 755 just for testing purposes but after a restart the permissions were 600 again. It's not like the config isn't saved but that it is overwritten by the default values.

**Comment by megamorphf** [comment]
I encountered the same Issue, I can verify that docker has nothing to do with it, because config overwrite  is done by transmission-daemon itself.
If you want to edit your configuration without overrides follow these steps:

1. docker stop transmission
2. _edit your configuration_
3. docker start transmission

Now the values will be kept as expected. I know that because I tried to install transmission-daemon on my actual machine and the behavior matched the one described.  Just remember that in order to edit your transmission configuration container/service has to be stopped.

Cheers!

**Comment by pedymaster** [comment]
I have just run into the same issue with settings. All my changes made through API gets lost upon stop of the container (wont get written into settings.json) I stop the container using the docker stop command.
I dont have any issues with transmission rewriting my settings json

Of course I can (and did) configure everything manually in settings json, but that is a workaround.

**Comment by frankicia** [comment]
At February 23, Transmission doesn't save settings changed through the web UI.  Settings.json is working.

**Comment by crkinard** [comment]
This seems to be happening again. Need to stop the container and edit the settings.json manually then start the container.
