### ISSUE TITLE
Volumes mapped to mounted shares on the host don't work properly

### ISSUE THREAD

**Issue by mscott83** [linuxserver/docker-transmission#71]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

When I run the transmission container on my compute host with volumes set to use mounted shares on a remote file server, the /config and /downloads/incomplete mounts work perfectly, but completed downloads are not added to the /mounted_share/transmission/downloads/complete folder - but they are visible inside the container's /downloads/complete folder.

If I change the volumes to use local folders on the host then it works fine, but I have to manually move the files to the share which is not ideal.  

Centos 7.5

Docker-compose.yml contents:
---
version: "2"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    volumes:
      - /mounted_share/transmission/config:/config
      - /mounted_share/transmission/downloads:/downloads
      - /mounted_share/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

The log contains nothing useful, no errors related to file moves at all.

Not using symlinks, but the host volume is a mounted CIFS share on a remote file server.

**Comment by tobbenb** [comment]
We don't recommend using cifs mounts for anything using our containers. It creates too many issues.
If the cifs share goes offline, and online again, the docker service will not see the mount until you restart the docker service.
You might also have permission issues.

As to your issue, since you can see the files inside the container, there might be something you didn't correctly configured inside transmission. What is your settings in transmission?
What is the output of ```ls -n``` in both /downloads and /mounted_share/transmission/downloads?

**Comment by thelamer** [comment]
no response and this is not a support platform , closing
